version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/nickvanw/bogon
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            go get -v -t -d ./...
            go test -v ./...
            cd cmd/bogon
            CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
            cp bogon ../../ && cd ../../
      - run:
          name: Build+Push Docker Image
          command: |
            TAG=`echo $CIRCLE_SHA1 | cut -c -7`
            docker login -p ${DOCKER_PASS} -u ${DOCKER_USERNAME} ${DOCKER_REG_HOST}
            docker build -t ${DOCKER_REG_HOST}/bogon:${TAG} .
            docker push ${DOCKER_REG_HOST}/bogon:${TAG}
