name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Binary
      run: |
        go get -v -t -d ./...
        cd cmd/bogon
        CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
        cp bogon ../../ && cd ../../ 
    
    - name: Build and Push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REPO }}
        tag_with_ref: false
        tag_with_sha: true
        repository: bogon
